name: troms_weather
channels:
  - conda-forge
dependencies:
  - python=3.13.1
  - pandas=2.2.3
  - geopandas=1.0.1
  - numpy=2.2.3
  - matplotlib=3.10.1
  - altair=5.5.0
  - requests=2.32.3
  - shapely=2.0.7
